// Decompiled with JetBrains decompiler
// Type: ProjectM.Sequencer.GraphFunction
// Assembly: ProjectM, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 83E42B70-D81B-4F1F-9FB5-6B5ABD5FF9FC
// Assembly location: C:\Users\mitch\.nuget\packages\vrising.unhollowed.client\0.6.5.57575090\lib\net6.0\ProjectM.dll

#nullable disable
namespace ProjectM.Sequencer
{
  public enum GraphFunction
  {
    None,
    InValue,
    OutValue,
    DebugValue,
    GraphTime,
    GraphDuration,
    LocalPlayerEntity,
    CameraTargetEntity,
    MousePosition,
    Add,
    Subtract,
    Multiply,
    Divide,
    Invert,
    Absolute,
    Distance,
    SquareRoot,
    Lerp,
    RotateVector,
    Min,
    Max,
    Split,
    Combine,
    Length,
    Normalize,
    DirectionToQuaternion,
    QuaternionToDirection,
    EulerToQuaternion,
    AxisAngleToQuaternion,
    FloatToInt,
    IntToFloat,
    LookRotation,
    GetHealthFromEntity,
    SubGraph,
    TranslationFromEntity,
    LifeTimeFromEntity,
    GetBoneFromEntity,
    GetBoneFromEntityAndType,
    GetModelScaleFromEntity,
    GetTeamFromEntity,
    GetIsLocalPlayerFromEntity,
    GetHUDHeightFromEntity,
    GetFuelFromEntity,
    GetAreAlliesFromEntity,
    EvaluateCurve,
    EvaluateThrowPosition,
    Compare,
    Selector,
    NOT,
    AND,
    OR,
    XOR,
    NAND,
    CopyBlackboardValue,
    IntConstant,
    Int2Constant,
    Int3Constant,
    Int4Constant,
    FloatConstant,
    Float2Constant,
    Float3Constant,
    Float4Constant,
    QuaternionConstant,
    BoneConstant,
  }
}
