// Decompiled with JetBrains decompiler
// Type: ProjectM.InputFlag
// Assembly: ProjectM.Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: CF03A298-FF93-4294-AFD6-565AD334A53C
// Assembly location: C:\Users\mitch\.nuget\packages\vrising.unhollowed.client\0.6.5.57575090\lib\net6.0\ProjectM.Shared.dll

#nullable disable
namespace ProjectM
{
  public enum InputFlag
  {
    None,
    Interact,
    Primary,
    WeaponSkill1,
    TravelSkill,
    CliffJump,
    WeaponSkill2,
    OffensiveSpell,
    DefensiveSpell,
    UltimateSpell,
    Ability4,
    ActionBar1,
    ActionBar2,
    ActionBar3,
    ActionBar4,
    ActionBar5,
    ActionBar6,
    ActionBar7,
    ActionBar8,
    ActionBar9,
    MapPan,
    MapZoom,
    MapMarker,
    VampirePowersMenu,
    InventoryManagementAbort,
    Interrupt,
    ToggleEmoteWheel,
    Building_Cancel,
    SplitItem,
    DropItem,
    Back,
    TransferItem,
    PushToTalk,
    VBloodMenu,
    CharacterMenu,
    BuildMenu,
    Building_RotateLeft,
    Building_RotateRight,
    Building_Place,
    Building_Deselect,
    MenuSelectionLeft,
    MenuSelectionRight,
    MenuSelectionUp,
    MenuSelectionDown,
    Building_Dismantle,
    RotateCamera,
    MapMenu,
    Respawn,
    ClanMenu,
    Chat,
    Enter,
    RepairItem,
    SpellBookMenu,
    SelectProgression,
    ToggleActionWheel,
    DisableAutoSnapPoints,
    DisableAutoSnapGrid,
    Shapeshift_Modifier,
    Shapeshift_1,
    Shapeshift_2,
    Shapeshift_3,
    Shapeshift_4,
    AutoMove,
    Building_Repair,
    Shapeshift_5,
    Shapeshift_6,
    Shapeshift_7,
    Shapeshift_8,
    Emotes_Modifier,
    Emotes_1,
    Emotes_2,
    Emotes_3,
    Emotes_4,
    Emotes_5,
    Emotes_6,
    Emotes_7,
    Emotes_8,
    CancelRevive,
    Building_ToggleColorWheel,
    TrackItem,
    AdvancedTooltip,
    EmotesMenu,
  }
}
